Luis
CS4992-AI-ML/open-house pull request #44
Opened 2024-07-24 23:44 UTC by P4rz1val22

2024-07-25 00:01 UTC, spencermendelsohn requested changes

2024-07-25 00:01 UTC, spencermendelsohn commented on src/clean-data.py
> +# df.loc[(df["Bathrooms"] == 0) & (df["Bedrooms"] != 0), "Bathrooms"] = np.round(
Remove unnecessary comments to clean up file

2024-07-25 00:01 UTC, spencermendelsohn commented on tests/housing-data-noAgencies.csv
Add this file to directory ***/Data***

2024-07-25 00:01 UTC, spencermendelsohn commented on tests/housing-data.csv
Same with this add it to the directory ***/Data***

2024-07-25 00:01 UTC, spencermendelsohn commented on tests/counting-agencies.py
> +name = "housing-data"
Change these directory names after you moved them to `/Data`

2024-07-25 00:19 UTC, spencermendelsohn requested changes

2024-07-25 00:19 UTC, spencermendelsohn commented on tests/counting-agencies.py
Recommend renaming to `tests/test-counting-agencies.py`

2024-07-26 00:22 UTC, P4rz1val22 commented on tests/counting-agencies.py
Moved to src cause it wasn't _really_ a test...

2024-07-26 00:31 UTC, spencermendelsohn approved these changes
SICK!!!

2024-07-26 00:32 UTC, Grant-diane approved these changes
yupp

2024-07-26 00:34 UTC, merged